session_secret: xyz
ripple:
  account_id: rXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  master_seed: sXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  host: s-east.ripple.com
  port: 51234
providers:
  developer:
    name: Developer
    uid: foo
    email: foo@example.com
  twitter:
    name: Twitter
    consumer_key: xxxxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  github:
    name: GitHub
    consumer_key: xxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
coins:
  sakuracoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9302
    symbol: SKR
    price: 50.0
  sha1coin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9512
    symbol: SHA
    price: 50.0
  sayacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 8332
    symbol: SYC
    price: 50.0
  monacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9402
    symbol: XMC
    price: 50.0
