ripple:
  account_id: rXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  master_seed: sXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  faucet:
    account_id: rXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    master_seed: sXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  host: s-east.ripple.com
  port: 51234
providers:
  developer:
    name: Developer
    uid: foo
    email: foo@example.com
  twitter:
    name: Twitter
    consumer_key: xxxxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  github:
    name: GitHub
    consumer_key: xxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  google_oauth2:
    name: Google
    consumer_key: x.apps.googleusercontent.com
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxx
locale: en
coins:
  bitcoin:
    host: 127.0.0.1
    port: 7777
    name: Bitcoin
    symbol: BTC
    fee: 0.0001
    txfee: 0.00002
    iou: false
    proxycoind: false
    electrum: true
    minconf: 0
  bitcoin:
    host: 127.0.0.1
    port: 7778
    name: Litecoin
    symbol: LTC
    fee: 0.01
    txfee: 0.001
    iou: false
    proxycoind: false
    electrum: true
    minconf: 0
  sakuracoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9302
    name: Sakuracoin
    symbol: SKR
    fee: 1.0
    iou: true
    proxycoind: false
    minconf: 36
  sha1coin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9512
    name: Sha1coin
    symbol: SHA
    fee: 1.0
    iou: true
    proxycoind: false
    minconf: 36
  sayacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 8332
    name: Sayacoin
    symbol: SYC
    fee: 1.0
    iou: true
    proxycoind: false
    minconf: 36
  monacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9402
    name: Monacoin
    symbol: XMC
    fee: 1.0
    iou: true
    proxycoind: false
  blackcoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 15715
    name: Blackcoin
    symbol: BKC
    fee: 1.0
    iou: true
    proxycoind: false
  kumacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 7585
    name: Kumacoin
    symbol: XKC
    fee: 1.0
    iou: true
    proxycoind: false
  yaycoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 8383
    name: yaycoin
    symbol: YAY
    fee: 1.0
    iou: true
    proxycoind: false
    minconf: 36
  ringo:
    user: user
    password: password
    host: 127.0.0.1
    port: 9292
    name: Ringo
    symbol: RIN
    fee: 1.0
    iou: true
    proxycoind: false
