session_secret: xyz
providers:
  twitter:
    consumer_key: xxxxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
sakuracoind:
  user: user
  password: password
  host: 127.0.0.1
  port: 9302
