session_secret: xyz
ripple:
  account_id: rXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  master_seed: sXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  host: 127.0.0.1
  port: 5005
providers:
  twitter:
    consumer_key: xxxxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  github:
    consumer_key: xxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
coins:
  sakuracoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9302
    symbol: SKR
  sha1coin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9512
    symbol: SHA
  sayacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 8332
    symbol: SYC
