session_secret: xyz
ripple:
  account_id: rXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  master_seed: sXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  faucet:
    account_id: rXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    master_seed: sXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  host: s-east.ripple.com
  port: 51234
providers:
  developer:
    name: Developer
    uid: foo
    email: foo@example.com
  twitter:
    name: Twitter
    consumer_key: xxxxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  github:
    name: GitHub
    consumer_key: xxxxxxxxxxxxxxxxxxxx
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  google_oauth2:
    name: Google
    consumer_key: x.apps.googleusercontent.com
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxx
coins:
  sakuracoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9302
    name: Sakuracoin
    symbol: SKR
    price: 50.0
    fee: 1.0
    iou: true
  sha1coin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9512
    name: Sha1coin
    symbol: SHA
    price: 50.0
    fee: 1.0
    iou: true
  sayacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 8332
    name: Sayacoin
    symbol: SYC
    price: 50.0
    fee: 1.0
    iou: true
  monacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 9402
    name: Monacoin
    symbol: XMC
    price: 50.0
    fee: 1.0
    iou: true
  blackcoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 15715
    name: Blackcoin
    symbol: BKC
    price: 50.0
    fee: 1.0
    iou: true
  kumacoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 7585
    name: Kumacoin
    symbol: XKC
    price: 50.0
    fee: 1.0
    iou: true
  yaycoin:
    user: user
    password: password
    host: 127.0.0.1
    port: 8383
    name: yaycoin
    symbol: YAY
    price: 50.0
    fee: 1.0
    iou: true
  ringo:
    user: user
    password: password
    host: 127.0.0.1
    port: 9292
    name: Ringo
    symbol: RIN
    price: 50.0
    fee: 1.0
    iou: true
